import { ArrowRight, BatteryWarning, Building2, Check, FileSearch, Fingerprint, Hand, LockKeyhole, ScanLine, ShieldCheck, Smartphone, WalletCards, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { Brand } from "../components/Brand";

const steps = ["Register", "Enroll palm", "Visit merchant", "Scan", "Confirm", "Pay"];

export function LandingPage() {
  return <div className="min-h-screen bg-white">
    <header className="absolute inset-x-0 top-0 z-20"><nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5" aria-label="Public navigation"><Brand /><div className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a href="#how">How it works</a><a href="#security">Security</a><a href="#merchants">For merchants</a></div><div className="flex items-center gap-2"><Link className="hidden rounded-xl px-4 py-2.5 text-sm font-semibold text-ink sm:block" to="/login">Log in</Link><Link className="btn-primary" to="/register">Get started <ArrowRight size={16} /></Link></div></nav></header>
    <main>
      <section className="hero-grid relative overflow-hidden bg-gradient-to-b from-forest-50/80 to-white pb-24 pt-36 sm:pt-44"><div className="absolute -right-40 top-20 size-[520px] rounded-full bg-emerald-200/30 blur-3xl" /><div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 lg:grid-cols-[1.06fr_.94fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-forest-100 bg-white px-3 py-2 text-xs font-semibold text-forest-700 shadow-sm"><span className="size-2 rounded-full bg-forest-500" />Built for Nepal · Prototype wallet</div><h1 className="max-w-3xl font-display text-5xl font-extrabold leading-[1.06] text-ink sm:text-6xl lg:text-7xl">Your Hand.<br /><span className="text-forest-600">Your Identity.</span><br />Your Payment.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">A contactless biometric payment prototype designed for fast and secure digital transactions in Nepal—even when your phone stays at home.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary px-6" to="/register">Try the demo <ArrowRight size={17} /></Link><Link className="btn-secondary px-6" to="/login?role=merchant"><Building2 size={17} />Merchant portal</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs font-medium text-slate-500"><span className="flex items-center gap-1.5"><Check size={15} className="text-forest-600" />No physical card</span><span className="flex items-center gap-1.5"><Check size={15} className="text-forest-600" />Simulated NPR wallet</span><span className="flex items-center gap-1.5"><Check size={15} className="text-forest-600" />Privacy-first prototype</span></div></div>
      <div className="relative mx-auto w-full max-w-[520px]"><div className="absolute -inset-6 rotate-3 rounded-[2.5rem] bg-gradient-to-br from-emerald-200/60 to-amber-100/50 blur-xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/70 bg-forest-900 p-5 shadow-glow sm:p-7"><div className="flex items-center justify-between text-white"><div><p className="text-xs text-emerald-100/60">NEPALGUNJ CAFE</p><p className="mt-1 font-display text-xl font-bold">Palm checkout</p></div><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs">NPR</span></div><div className="my-6 rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-xs text-emerald-100/60">Amount due</p><p className="mt-1 font-display text-4xl font-bold text-white">Rs. 650<span className="text-lg text-emerald-200/60">.00</span></p></div><div className="palm-lines relative mx-auto grid aspect-square max-w-[260px] place-items-center overflow-hidden rounded-[35%] border border-white/20"><Hand className="size-28 text-white/90" strokeWidth={1.1} /><div className="scan-line absolute left-[12%] right-[12%] top-1/2 h-px bg-emerald-200 shadow-[0_0_16px_#a7f3d0]" /></div><div className="mt-6 flex items-center justify-center gap-2 text-sm text-emerald-100"><ScanLine size={17} className="text-emerald-300" />Ready for palm</div></div><div className="absolute -bottom-5 -left-7 hidden rounded-2xl border border-slate-100 bg-white p-4 shadow-card sm:block"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Zap size={19} /></span><div><p className="text-xs text-slate-500">Typical demo flow</p><p className="font-display font-bold text-ink">Scan · Confirm · Pay</p></div></div></div></div></div></section>

      <section id="how" className="mx-auto max-w-7xl px-5 py-24"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">How it works</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">From open palm to paid</h2><p className="mt-4 leading-7 text-slate-500">A simple customer journey backed by separate identity, risk, authorization, and wallet layers.</p></div><div className="mt-14 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{steps.map((step, index) => <div className="relative rounded-2xl border border-slate-200 bg-white p-5 text-center shadow-sm" key={step}><span className="mx-auto grid size-10 place-items-center rounded-xl bg-forest-50 font-display text-sm font-bold text-forest-700">{index + 1}</span><p className="mt-4 text-sm font-semibold text-ink">{step}</p>{index < steps.length - 1 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden size-5 rounded-full bg-white text-slate-300 lg:block" />}</div>)}</div></section>

      <section className="bg-forest-900 py-24 text-white"><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 lg:grid-cols-2"><div><p className="eyebrow !text-emerald-300">Life keeps moving</p><h2 className="mt-3 text-4xl font-bold text-white">No phone required at checkout.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-emerald-50/65">Your enrolled biometric identity links to your demo wallet. The merchant terminal handles checkout while the customer confirms the payment.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{[[WalletCards,"Forgot your wallet?"],[BatteryWarning,"Battery is dead?"],[Smartphone,"Phone left at home?"]].map(([Icon,label]) => { const I = Icon as typeof Hand; return <div key={label as string} className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><I className="size-5 text-emerald-300" /><p className="mt-3 text-sm font-semibold">{label as string}</p></div>})}</div></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-white p-6 text-ink sm:translate-y-6"><Fingerprint className="size-8 text-forest-600" /><h3 className="mt-5 text-xl font-bold">Biometric identity</h3><p className="mt-2 text-sm leading-6 text-slate-500">A feature template identifies the enrolled customer. Raw images are not retained by default.</p></div><div className="rounded-3xl border border-white/10 bg-white/10 p-6"><LockKeyhole className="size-8 text-emerald-300" /><h3 className="mt-5 text-xl font-bold text-white">Separate authorization</h3><p className="mt-2 text-sm leading-6 text-emerald-50/60">Riskier payments step up to a PIN. A palm match alone never moves wallet funds.</p></div></div></div></section>

      <section id="security" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Security by design</p><h2 className="mt-3 text-4xl font-bold">Built like a fintech system, labeled like a prototype.</h2><p className="mt-5 leading-7 text-slate-500">RGB-camera palm matching is useful for learning and demonstration, but it is not equivalent to certified palm-print and palm-vein hardware. We make that limitation explicit.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[ShieldCheck,"Risk-based approval","Transaction amount, scan failures, velocity, time, and account changes contribute to a server-side risk score."],[LockKeyhole,"Protected money movement","Integer paisa calculations, idempotency, explicit states, and atomic database transfers reduce common payment failure modes."],[Fingerprint,"Biometric privacy","Templates live outside normal profiles and can be deleted. Receipts never contain biometric details."],[FileSearch,"Accountability","Security events and append-style audit logs support investigation without exposing secrets."]].map(([Icon,title,text]) => { const I=Icon as typeof Hand; return <article key={title as string} className="card"><I className="size-6 text-forest-600" /><h3 className="mt-4 text-lg font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text as string}</p></article>})}</div></section>

      <section id="merchants" className="mx-auto max-w-7xl px-5 pb-24"><div className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-forest-600 to-forest-900 p-8 text-white sm:p-12"><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><p className="text-sm font-semibold text-emerald-200">For Nepali merchants</p><h2 className="mt-2 text-3xl font-bold text-white">A checkout your staff can learn in minutes.</h2><p className="mt-3 max-w-2xl text-emerald-50/70">Enter the NPR amount, ask for a palm, confirm, and receive a digital receipt—with live status updates throughout.</p></div><Link className="btn bg-white text-forest-800 hover:bg-emerald-50" to="/register?role=merchant">Create merchant account <ArrowRight size={17} /></Link></div></div></section>
    </main>
    <footer className="border-t border-slate-200 bg-[#f6faf8]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 py-8 sm:flex-row sm:items-center"><Brand /><p className="max-w-xl text-xs leading-5 text-slate-500">Educational and portfolio prototype using simulated funds. Not a bank, payment provider, or production biometric system.</p></div></footer>
  </div>;
}
