import { useEffect, useState, type FormEvent } from "react";
import { LockKeyhole, Save, ShieldAlert, UserRound } from "lucide-react";
import { Loading, Notice, PageTitle, Status } from "../components/Ui";
import { useAuth } from "../context/AuthContext";
import { useLoad } from "../hooks/useLoad";
import { api } from "../lib/api";

interface Profile {id:string;email:string;displayName:string;phone?:string;role:string;emailVerified:boolean;status:string;profile?:{address?:string;district?:string;preferredLanguage?:string}}
export function ProfilePage(){const {user}=useAuth();const {data,error,loading,reload}=useLoad(()=>api.get<Profile>("/users/profile"),[]);const [message,setMessage]=useState("");const [actionError,setActionError]=useState("");const [busy,setBusy]=useState(false);useEffect(()=>setActionError(error),[error]);if(loading)return <Loading/>;
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setActionError("");try{await api.patch("/users/profile",{displayName:f.get("displayName"),phone:f.get("phone"),address:f.get("address"),district:f.get("district"),preferredLanguage:f.get("preferredLanguage")});setMessage("Profile updated.");await reload()}catch(err){setActionError(err instanceof Error?err.message:"Update failed.")}finally{setBusy(false)}}
 async function pin(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setActionError("");try{await api.post("/users/payment-pin",{password:f.get("password"),pin:f.get("pin")});setMessage("Payment PIN changed.");e.currentTarget.reset()}catch(err){setActionError(err instanceof Error?err.message:"PIN change failed.")}finally{setBusy(false)}}
 async function freeze(){if(!data)return;const freeze=data.status!=="FROZEN";if(freeze&&!window.confirm("Freeze your account and wallet? New payments will be blocked."))return;setBusy(true);try{await api.post("/users/freeze",{freeze});setMessage(freeze?"Account frozen.":"Account reactivated.");await reload()}catch(err){setActionError(err instanceof Error?err.message:"Status update failed.")}finally{setBusy(false)}}
 return <><PageTitle eyebrow="Account" title={user?.role==="ADMIN"?"System configuration & profile":"Profile & settings"} description="Manage personal information and security controls."/>{actionError&&<div className="mb-5"><Notice>{actionError}</Notice></div>}{message&&<div className="mb-5"><Notice tone="success">{message}</Notice></div>}{data&&<div className="grid gap-6 xl:grid-cols-[1fr_.8fr]"><form className="card" onSubmit={save}><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-forest-50 text-forest-600"><UserRound size={22}/></div><div><h2 className="text-lg font-bold">Personal information</h2><p className="text-xs text-slate-500">Role: {data.role}</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="label">Display name<input className="input" name="displayName" defaultValue={data.displayName} required/></label><label className="label">Email<input className="input bg-slate-50" value={data.email} disabled/></label><label className="label">Phone<input className="input" name="phone" defaultValue={data.phone}/></label>{user?.role==="CUSTOMER"&&<><label className="label">District<input className="input" name="district" defaultValue={data.profile?.district}/></label><label className="label sm:col-span-2">Address<input className="input" name="address" defaultValue={data.profile?.address}/></label><label className="label">Language<select name="preferredLanguage" className="input" defaultValue={data.profile?.preferredLanguage||"en"}><option value="en">English</option><option value="ne">नेपाली</option></select></label></>}</div><button className="btn-primary mt-6" disabled={busy}><Save size={17}/>Save changes</button></form><div className="space-y-6"><section className="card"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">Account status</p><div className="mt-2"><Status value={data.status}/></div></div><LockKeyhole className="text-forest-600"/></div>{user?.role==="CUSTOMER"&&<button className={data.status==="FROZEN"?"btn-primary mt-5 w-full":"btn-danger mt-5 w-full"} disabled={busy} onClick={()=>void freeze()}>{data.status==="FROZEN"?"Reactivate account":"Freeze account"}</button>}</section>{user?.role==="CUSTOMER"&&<form className="card" onSubmit={pin}><h2 className="text-lg font-bold">Change payment PIN</h2><p className="mt-1 text-sm text-slate-500">Required for high-risk palm payments.</p><label className="label mt-4">Current password<input name="password" type="password" className="input" required/></label><label className="label mt-4">New 4–8 digit PIN<input name="pin" type="password" inputMode="numeric" pattern="\d{4,8}" className="input" required/></label><button className="btn-secondary mt-5 w-full" disabled={busy}>Update PIN</button></form>}{user?.role==="ADMIN"&&<ConfigCard/>}</div></div>}</>}

function ConfigCard(){const [value,setValue]=useState("20000");const [message,setMessage]=useState("");return <section className="card"><div className="flex items-center gap-2"><ShieldAlert className="text-amber-600"/><h2 className="text-lg font-bold">Risk configuration</h2></div><label className="label mt-4">High-value PIN threshold (NPR)<input className="input" type="number" min="1" value={value} onChange={(e)=>setValue(e.target.value)}/></label><button className="btn-secondary mt-4" onClick={()=>void api.put("/admin/configuration/highValuePinThreshold",{value:Number(value),description:"NPR threshold requiring payment PIN"}).then(()=>setMessage("Configuration saved."))}>Save threshold</button>{message&&<p className="mt-3 text-sm text-emerald-700">{message}</p>}</section>}
