import { Activity, AlertTriangle, CheckCircle2, LockKeyhole, ShieldAlert, XCircle } from "lucide-react";
import { Empty, Loading, Notice, PageTitle, Status } from "../components/Ui";
import { useAuth } from "../context/AuthContext";
import { useLoad } from "../hooks/useLoad";
import { api } from "../lib/api";
import { dateTime } from "../lib/format";

interface EventItem {_id:string;category:string;action:string;severity:string;success:boolean;createdAt:string;metadata?:Record<string,unknown>}
interface AlertItem {_id:string;riskScore:number;riskLevel:string;indicators:string[];status:string;createdAt:string;userId?:{displayName:string;email:string}}
export function SecurityPage(){const {user}=useAuth();const privileged=user?.role==="ADMIN"||user?.role==="AUDITOR";const {data,error,loading}=useLoad(async()=>{const events=await api.get<{items:EventItem[]}>("/security/events?limit=50");const alerts=privileged?await api.get<AlertItem[]>("/security/alerts"):[];return {events:events.items,alerts}},[privileged]);if(loading)return <Loading label="Loading security events…"/>;if(error||!data)return <Notice>{error||"Security data unavailable."}</Notice>;
 return <><PageTitle eyebrow="Monitoring" title="Security centre" description={privileged?"Read authentication, palm, payment, system events, and risk alerts across the platform.":"Review security activity connected to your account."}/><div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><section className="card"><div className="mb-5 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-forest-50 text-forest-600"><Activity size={20}/></div><div><h2 className="text-lg font-bold">Security event timeline</h2><p className="text-xs text-slate-500">Newest activity first</p></div></div>{data.events.length?<div className="space-y-1">{data.events.map((event)=><article key={event._id} className="flex gap-3 rounded-xl p-3 hover:bg-slate-50"><div className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-full ${event.success?"bg-emerald-100 text-emerald-700":"bg-red-100 text-red-600"}`}>{event.success?<CheckCircle2 size={16}/>:<XCircle size={16}/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-ink">{event.action.replaceAll("_"," ")}</p><span className="text-xs text-slate-400">{dateTime(event.createdAt)}</span></div><div className="mt-1 flex items-center gap-2"><span className="text-xs text-slate-500">{event.category}</span><Status value={event.severity}/></div></div></article>)}</div>:<Empty title="No security events" detail="Authentication and payment security activity will appear here."/>}</section><div className="space-y-6"><section className="card"><LockKeyhole className="text-forest-600"/><h2 className="mt-4 text-lg font-bold">Security model</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-500"><li>• Palm establishes biometric identity.</li><li>• Risk rules choose the approval step.</li><li>• High-risk payments require a PIN.</li><li>• Repeated failures create alerts.</li></ul></section>{privileged&&<section className="card"><div className="flex items-center gap-2"><ShieldAlert className="text-amber-600"/><h2 className="text-lg font-bold">Risk alerts</h2></div><div className="mt-4 space-y-3">{data.alerts.length?data.alerts.slice(0,8).map((alert)=><article className="rounded-xl border border-slate-200 p-3" key={alert._id}><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold">{alert.userId?.displayName||"Platform event"}</p><p className="mt-1 text-xs text-slate-500">{alert.indicators.join(", ").replaceAll("_"," ")}</p></div><Status value={alert.riskLevel}/></div><div className="mt-3 flex justify-between text-xs text-slate-400"><span>Score {alert.riskScore}</span><span>{alert.status}</span></div></article>):<p className="text-sm text-slate-500">No risk alerts.</p>}</div></section>}</div></div></>}
